site_name: Secure CINC Auditor Kubernetes Container Scanning
site_url: http://localhost:8000/
site_description: A comprehensive platform for securely scanning Kubernetes containers
site_author: MITRE SAF Team
copyright: © The MITRE Corporation. Brought to you by the <a href="https://saf.mitre.org">MITRE Security Automation Framework (SAF)</a>

repo_name: mitre/kube-cinc-secure-scanner
repo_url: https://github.com/mitre/kube-cinc-secure-scanner
edit_uri: edit/main/docs/

# Configure documentation directories
docs_dir: docs

# Exclude non-documentation files from processing
exclude_docs: |
  # Node.js related files
  node_modules/*
  */node_modules/*
  docs/node_modules/*
  package.json
  */package.json
  docs/package.json
  package-lock.json
  */package-lock.json
  docs/package-lock.json
  
  # Python related files
  requirements.txt
  */requirements.txt
  docs/requirements.txt
  
  # Exclude files that conflict with index.md files
  /README.md
  # All README.md files from docs directory are now included in navigation

theme:
  name: material
  custom_dir: docs/theme_overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.code.link
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ['.', 'docs', 'includes']
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra_css:
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - js/mermaid-config.js

plugins:
  - search
  - mkdocstrings


nav:
  # Getting Started
  - Getting Started:
    - Introduction: index.md
    - Executive Summary: overview/executive-summary.md
    - Quickstart Guide: quickstart-guide.md
    - Technical Overview: overview/index.md
    - Enterprise Integration: overview/enterprise-integration-analysis.md
  
  # Core Concepts
  - Core Concepts:
    - Architecture:
      - Overview: architecture/index.md
      - Workflow Diagrams: architecture/diagrams/index.md
      - Workflow Processes: architecture/workflows/index.md
      - Directory Contents: architecture/inventory.md
    - Scanning Approaches:
      - Overview: approaches/index.md
      - Comparison: approaches/comparison.md
      - Decision Matrix: approaches/decision-matrix.md
      - Directory Contents: approaches/inventory.md
      - Kubernetes API Approach:
        - Overview: approaches/kubernetes-api/index.md
        - Directory Contents: approaches/kubernetes-api/inventory.md
        - Technical Implementation: approaches/kubernetes-api/implementation.md
        - RBAC Configuration: approaches/kubernetes-api/rbac.md
        - Limitations: approaches/kubernetes-api/limitations.md
      - Debug Container Approach:
        - Overview: approaches/debug-container/index.md
        - Directory Contents: approaches/debug-container/inventory.md
        - Distroless Container Basics: approaches/debug-container/distroless-basics.md
        - Technical Implementation: approaches/debug-container/implementation.md
      - Sidecar Container Approach:
        - Overview: approaches/sidecar-container/index.md
        - Directory Contents: approaches/sidecar-container/inventory.md
        - Technical Implementation: approaches/sidecar-container/implementation.md
      - Helper Scripts:
        - Overview: approaches/helper-scripts/index.md
        - Directory Contents: approaches/helper-scripts/inventory.md
        - Scripts vs. Commands: approaches/helper-scripts/scripts-vs-commands.md
    - Security:
      - Overview: security/index.md
      - Directory Contents: security/inventory.md
      - Security Principles:
        - Overview: security/principles/index.md
        - Directory Contents: security/principles/inventory.md
        - Least Privilege: security/principles/least-privilege.md
        - Ephemeral Credentials: security/principles/ephemeral-creds.md
        - Resource Isolation: security/principles/resource-isolation.md
        - Secure Transport: security/principles/secure-transport.md
      - Risk Analysis:
        - Overview: security/risk/index.md
        - Directory Contents: security/risk/inventory.md
        - Risk Model: security/risk/model.md
        - Kubernetes API Approach: security/risk/kubernetes-api.md
        - Debug Container Approach: security/risk/debug-container.md
        - Sidecar Container Approach: security/risk/sidecar-container.md
        - Risk Mitigations: security/risk/mitigations.md
      - Threat Model:
        - Overview: security/threat-model/index.md
        - Directory Contents: security/threat-model/inventory.md
        - Attack Vectors: security/threat-model/attack-vectors.md
        - Lateral Movement: security/threat-model/lateral-movement.md
        - Token Exposure: security/threat-model/token-exposure.md
        - Threat Mitigations: security/threat-model/threat-mitigations.md
      - Compliance:
        - Overview: security/compliance/index.md
        - Directory Contents: security/compliance/inventory.md
        - Approach Comparison: security/compliance/approach-comparison.md
        - Risk Documentation: security/compliance/risk-documentation.md
      - Recommendations:
        - Overview: security/recommendations/index.md
        - Directory Contents: security/recommendations/inventory.md
  
  # Deployment & Configuration
  - Deployment & Configuration:
    - Kubernetes Setup:
      - Overview: kubernetes-setup/index.md
      - Directory Contents: kubernetes-setup/inventory.md
    - RBAC Configuration:
      - Basic RBAC: rbac/index.md
      - Label-based RBAC: rbac/label-based.md
      - Directory Contents: rbac/inventory.md
    - Configuration:
      - Overview: configuration/index.md
      - Directory Contents: configuration/inventory.md
      - Kubeconfig:
        - Overview: configuration/kubeconfig/index.md
        - Directory Contents: configuration/kubeconfig/inventory.md
        - Generation: configuration/kubeconfig/generation.md
        - Management: configuration/kubeconfig/management.md
        - Security: configuration/kubeconfig/security.md
        - Dynamic Configuration: configuration/kubeconfig/dynamic.md
      - Thresholds:
        - Overview: configuration/thresholds/index.md
        - Directory Contents: configuration/thresholds/inventory.md
        - Basic Configuration: configuration/thresholds/basic.md
        - Advanced Configuration: configuration/thresholds/advanced.md
        - Example Configurations: configuration/thresholds/examples.md
        - CI/CD Integration: configuration/thresholds/cicd.md
      - Plugin Customization:
        - Overview: configuration/plugins/index.md
        - Directory Contents: configuration/plugins/inventory.md
        - Distroless Support: configuration/plugins/distroless.md
        - Implementation Guide: configuration/plugins/implementation.md
        - Testing Guide: configuration/plugins/testing.md
      - Integration:
        - Overview: configuration/integration/index.md
        - Directory Contents: configuration/integration/inventory.md
        - SAF CLI Integration: configuration/integration/saf-cli.md
        - GitHub Actions: configuration/integration/github.md
        - GitLab CI: configuration/integration/gitlab.md
      - Security:
        - Overview: configuration/security/index.md
        - Directory Contents: configuration/security/inventory.md
        - Hardening: configuration/security/hardening.md
        - Credential Management: configuration/security/credentials.md
        - RBAC Configuration: configuration/security/rbac.md
    - Authentication:
      - Token Management: tokens/index.md
      - Service Accounts: service-accounts/index.md
    - Helm Charts:
      - Introduction: helm-charts/index.md
      - Directory Contents: helm-charts/inventory.md
      - Overview:
        - Introduction: helm-charts/overview/index.md
        - Directory Contents: helm-charts/overview/inventory.md
        - Architecture: helm-charts/overview/architecture.md
      - Scanner Types:
        - Introduction: helm-charts/scanner-types/index.md
        - Directory Contents: helm-charts/scanner-types/inventory.md
        - Common Scanner: helm-charts/scanner-types/common-scanner.md
        - Kubernetes API Scanner: helm-charts/scanner-types/standard-scanner.md
        - Debug Container Scanner: helm-charts/scanner-types/distroless-scanner.md
        - Sidecar Container Scanner: helm-charts/scanner-types/sidecar-scanner.md
      - Infrastructure:
        - Overview: helm-charts/infrastructure/index.md
        - Directory Contents: helm-charts/infrastructure/inventory.md
        - RBAC Configuration: helm-charts/infrastructure/rbac.md
        - Service Accounts: helm-charts/infrastructure/service-accounts.md
        - Namespaces: helm-charts/infrastructure/namespaces.md
      - Usage & Customization:
        - Overview: helm-charts/usage/index.md
        - Directory Contents: helm-charts/usage/inventory.md
        - Customization Guide: helm-charts/usage/customization.md
        - Configuration Reference: helm-charts/usage/configuration.md
        - Values Files: helm-charts/usage/values.md
      - Security:
        - Overview: helm-charts/security/index.md
        - Directory Contents: helm-charts/security/inventory.md
        - Best Practices: helm-charts/security/best-practices.md
        - RBAC Hardening: helm-charts/security/rbac-hardening.md
        - Risk Assessment: helm-charts/security/risk-assessment.md
      - Operations:
        - Overview: helm-charts/operations/index.md
        - Directory Contents: helm-charts/operations/inventory.md
        - Troubleshooting: helm-charts/operations/troubleshooting.md
        - Performance: helm-charts/operations/performance.md
        - Maintenance: helm-charts/operations/maintenance.md
  
  # Integration
  - CI/CD Integration:
    - Overview: integration/index.md
    - Directory Contents: integration/inventory.md
    - Approach Mapping: integration/approach-mapping.md
    - Analysis: integration/gitlab-services-analysis.md
    - CI/CD Platforms:
      - Overview: integration/platforms/index.md
      - Directory Contents: integration/platforms/inventory.md
      - GitHub Actions: integration/platforms/github-actions.md
      - GitLab CI: integration/platforms/gitlab-ci.md
      - GitLab Services: integration/platforms/gitlab-services.md
    - Integration Workflows:
      - Overview: integration/workflows/index.md
      - Directory Contents: integration/workflows/inventory.md
      - Standard Container: integration/workflows/standard-container.md
      - Distroless Container: integration/workflows/distroless-container.md
      - Sidecar Container: integration/workflows/sidecar-container.md
      - Security Workflows: integration/workflows/security-workflows.md
    - Integration Examples:
      - Overview: integration/examples/index.md
      - Directory Contents: integration/examples/inventory.md
      - GitHub Examples: integration/examples/github-examples.md
      - GitLab Examples: integration/examples/gitlab-examples.md
    - Integration Configuration:
      - Overview: integration/configuration/index.md
      - Directory Contents: integration/configuration/inventory.md
      - Environment Variables: integration/configuration/environment-variables.md
      - Secrets Management: integration/configuration/secrets-management.md
      - Thresholds Integration: integration/configuration/thresholds-integration.md
      - Reporting Configuration: integration/configuration/reporting.md
    - Example Resources:
      - GitHub Workflow Examples: github-workflow-examples/index.md
      - GitHub Workflow Contents: github-workflow-examples/inventory.md
      - GitLab Pipeline Examples: gitlab-pipeline-examples/index.md
      - GitLab Pipeline Contents: gitlab-pipeline-examples/inventory.md
      - GitLab Services Examples: gitlab-services-examples/index.md
      - Code Examples: examples/index.md
      - Code Display Demo: examples/code-display-demo.md
      - Examples Directory Contents: examples/inventory.md
  
  # Development & Contributing
  - Development:
    - Developer Guide:
      - Overview: developer-guide/index.md
      - Directory Contents: developer-guide/inventory.md
    - Testing: 
      - Overview: developer-guide/testing/index.md
      - Directory Contents: developer-guide/testing/inventory.md
    - Deployment: 
      - Overview: developer-guide/deployment/index.md
      - Directory Contents: developer-guide/deployment/inventory.md
      - Deployment Methods:
        - Script Deployment: developer-guide/deployment/script-deployment.md
        - Helm Deployment: developer-guide/deployment/helm-deployment.md
        - CI/CD Integration: developer-guide/deployment/cicd-deployment.md
      - Deployment Scenarios:
        - Overview: developer-guide/deployment/scenarios/index.md
        - Enterprise Environment: developer-guide/deployment/scenarios/enterprise.md
        - Development Environment: developer-guide/deployment/scenarios/development.md
        - CI/CD Environment: developer-guide/deployment/scenarios/cicd.md
        - Multi-Tenant Environment: developer-guide/deployment/scenarios/multi-tenant.md
        - Air-Gapped Environment: developer-guide/deployment/scenarios/air-gapped.md
      - Advanced Topics:
        - Overview: developer-guide/deployment/advanced-topics/index.md
        - Directory Contents: developer-guide/deployment/advanced-topics/inventory.md
        - Scaling and Performance: developer-guide/deployment/advanced-topics/scaling.md
        - Security Enhancements: developer-guide/deployment/advanced-topics/security.md
        - Monitoring and Maintenance: developer-guide/deployment/advanced-topics/monitoring.md
        - Specialized Environments: developer-guide/deployment/advanced-topics/specialized-environments.md
        - Deployment Verification: developer-guide/deployment/advanced-topics/verification.md
        - Custom Development: developer-guide/deployment/advanced-topics/custom-development.md
    - Contributing:
      - Overview: contributing/index.md
      - Directory Contents: contributing/inventory.md
      - Documentation Tools: contributing/documentation-tools.md
      - STIG/SRG API Tools: contributing/stig-api-tools.md
      - Code Snippets: contributing/code-snippets.md
      - Diagram Color Guide: contributing/diagram-color-guide.md
      - Documentation Testing:
        - Overview: contributing/testing/index.md
        - Directory Contents: contributing/testing/inventory.md
        - Theme Testing: contributing/testing/dark-light-mode-test.md
  
  # Project Information
  - Project:
    - Overview: project/index.md
    - Changelog: project/changelog.md
    - Roadmap: project/roadmap.md
    - Tasks: project/tasks.md
    - Documentation:
      - Directory Contents: project/inventory.md
      - Documentation Gaps: project/documentation-gaps.md
      - Content Map: project/content-map.md
      - Documentation Refactoring: project/documentation-entry-refactoring.md
      - Documentation Review Plan: project/documentation-review-plan.md
      - Documentation Cleanup Progress: project/documentation-cleanup-progress.md
      - Warning Resolution Scripts: project/warning-resolution-scripts.md
      - Terminology: project/terminology.md
      - Abbreviations: includes/abbreviations.md
      - Reorganization Summaries:
        - Integration Reorganization: project/integration-reorganization-summary.md
        - Architecture Reorganization: project/architecture-reorganization-summary.md
        - Configuration Reorganization: project/configuration-reorganization-summary.md
        - Helm Charts Reorganization: project/helm-charts-reorganization-summary.md
        - Security Reorganization: project/security-reorganization-summary.md
        - Documentation Structure: project/documentation-structure-progress.md
    - Tools & Utilities:
      - Overview: utilities/index.md
      - Directory Contents: utilities/inventory.md
      - Documentation Tools: project/documentation-tools.md
      - ASCII to Mermaid Conversion: utilities/ascii-to-mermaid.md
    - Archive:
      - Overview: project/archive/index.md
      - Directory Contents: project/archive/inventory.md
      - ASCII Diagrams: project/archive/ascii-diagrams.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mitre
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mitre
    - icon: fontawesome/solid/shield
      link: https://saf.mitre.org
      name: MITRE Security Automation Framework
  version:
    provider: mike