# Default values for distroless-scanner
# This is a YAML-formatted file

# Common scanner configuration
common-scanner:
  # Pass-through values for scanner-infrastructure
  scanner-infrastructure:
    targetNamespace: inspec-test
    serviceAccount:
      create: true
      name: inspec-scanner
    rbac:
      create: true
      rules:
        ephemeralContainers:
          enabled: true
  
  # Script configuration
  scripts:
    generate: true
    includeScanScript: true
    includeDistrolessScanScript: true

# Test pod configuration
testPod:
  # Deploy a test pod
  deploy: true
  # Name of the test pod
  name: distroless-target
  # Container name
  containerName: distroless
  # Container image (using Google's distroless as an example)
  image: gcr.io/distroless/static-debian11:latest
  # Command to run in the container
  command: ["/bin/sleep", "infinity"]
  # Labels for the pod
  labels:
    app: distroless-target
    scan-target: "true"
    distroless: "true"

# Debug container configuration for distroless scanning
debugContainer:
  # Enable debug container support
  enabled: true
  # Image to use for debug container
  image: docker.io/cincproject/auditor:latest
  # Default name prefix for the debug container
  namePrefix: debug
  # Default timeout for debug container in seconds
  timeoutSeconds: 300
  # Additional args for the debug container
  additionalArgs: []

# CINC Auditor configuration
cincAuditor:
  # Default profile to use for scanning
  defaultProfile: ""
  # Additional inspec.yml configuration
  inspecYml:
    name: distroless-baseline
    title: Distroless Container Security Baseline
    version: 1.0.0
    supports:
      - platform: k8s