apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
  namespace: pipeline
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
  resourceNames: ["inspec-target"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
  resourceNames: ["inspec-target"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: pipeline
roleRef:
  kind: Role
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openapi-schema-reader
rules:
- nonResourceURLs:
  - /openapi
  - /openapi/*
  - /openapi/v2
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openapi-schema-reader-binding
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: pipeline
roleRef:
  kind: ClusterRole
  name: openapi-schema-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: pipeline-secret
  annotations:
    kubernetes.io/service-account.name: pipeline