apiVersion: v1
kind: ServiceAccount
metadata:
  name: inspec-scanner
  namespace: inspec-test
  labels:
    app: inspec-scanner
    purpose: security-scanning
  annotations:
    description: "Service account for InSpec container scanning"