# Default values for sidecar-scanner
# This is a YAML-formatted file

# Common scanner configuration
common-scanner:
  # Pass-through values for scanner-infrastructure
  scanner-infrastructure:
    targetNamespace: inspec-test
    serviceAccount:
      create: true
      name: inspec-scanner
    rbac:
      create: true
      rules:
        podExec:
          enabled: true
  
  # Script configuration
  scripts:
    generate: true
    includeScanScript: true
    includeSidecarScanScript: true

# Test pod configuration
testPod:
  # Deploy a test pod
  deploy: true
  # Name of the test pod
  name: sidecar-target
  # Target container name
  targetContainer:
    name: target
    # Container image to scan
    image: busybox:latest
    # Command to run in the container
    command: ["/bin/sleep", "infinity"]
  # Labels for the pod
  labels:
    app: sidecar-target
    scan-target: "true"

# Sidecar scanner configuration
sidecarScanner:
  # Enable sidecar scanner
  enabled: true
  # Container name
  name: scanner
  # Scanner image 
  image: docker.io/cincproject/auditor:latest
  # Resource limits for the scanner
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  # Security context
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

# Shared Process Namespace configuration
sharedProcessNamespace:
  enabled: true

# CINC Auditor configuration
cincAuditor:
  # Default profile to use for scanning
  defaultProfile: ""
  # Additional inspec.yml configuration
  inspecYml:
    name: container-baseline
    title: Container Security Baseline
    version: 1.0.0
    supports:
      - platform: linux

# Volumes for scanner
volumes:
  # Results volume
  results:
    name: scan-results
    emptyDir: {}
  # Profiles volume
  profiles:
    name: inspec-profiles
    configMap:
      name: ""
  # Thresholds volume
  thresholds:
    name: inspec-thresholds
    configMap:
      name: ""