{{- if .Values.targetNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.targetNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    purpose: security-scanning
{{- end }}