{{- if .Values.testPod.deploy }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.testPod.name }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.testPod.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  containers:
  - name: {{ .Values.testPod.name }}
    image: {{ .Values.testPod.image }}
    command: {{ .Values.testPod.command }}
{{- end }}