apiVersion: v2
name: scanner-infrastructure
description: Core infrastructure for secure Kubernetes container scanning
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - security
  - compliance
  - scanning
  - kubernetes
  - rbac
maintainers:
  - name: Security Team